# Qiyas Crop Yield Hackathon — A: Data Cleaning & Integration Pipeline

Consolidated notebook for Deliverable **A** (14 pts).  
All cleaning, standardization, joins, feature engineering, integrity checks, and master-table export are performed here so the **exact same pipeline** can be applied to train and test (Rule 6).

## 0. Imports & Paths

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# Paths (relative — never absolute)
RAW_DIR = Path("../data/raw")
PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH   = RAW_DIR / "crop_yield_train.csv"
TEST_PATH    = RAW_DIR / "crop_yield_leaderboard_test.csv"
WEATHER_PATH = RAW_DIR / "regional_weather.csv"
PRICE_PATH   = RAW_DIR / "market_prices.csv"

print("Libraries and paths ready")

Libraries and paths ready

## 1. Load Raw Data

In [2]:
#  -- load the datsets and explore the data  
train   = pd.read_csv(TRAIN_PATH)
test    = pd.read_csv(TEST_PATH)
weather = pd.read_csv(WEATHER_PATH)
prices  = pd.read_csv(PRICE_PATH)

print("TRAIN  :", train.shape)
print("TEST   :", test.shape)
print("WEATHER:", weather.shape)
print("PRICES :", prices.shape)
print("\nTRAIN columns:", train.columns.tolist())
print("WEATHER columns:", weather.columns.tolist())
print("PRICES columns :", prices.columns.tolist())

TRAIN  : (15090, 15)
TEST   : (3750, 14)
WEATHER: (232, 6)
PRICES : (100, 4)

TRAIN columns: ['plot_id', 'region', 'crop_type', 'survey_year', 'planting_month', 'altitude_m', 'rainfall_mm_season', 'farm_size_ha', 'fertilizer_kg_per_ha', 'improved_seed_used', 'pest_disease_flag', 'soil_quality_index', 'labor_days_per_ha', 'distance_to_market_km', 'yield_tons_per_ha']
WEATHER columns: ['region', 'year', 'month', 'avg_temp_c', 'monthly_rainfall_mm', 'extreme_heat_days']
PRICES columns : ['crop_type', 'region', 'year', 'price_birr_per_quintal']

## A1 — Cleaning Log

One row per issue: file, column(s), issue type, rows affected (count & %), fix applied, and rationale.  
Covers ≥4 distinct issues in the plot files, ≥2 in weather, ≥2 in prices.

In [3]:
# ---------- Exploratory audit (before any cleaning) ----------
def missing_report(df, name):
    miss = df.isna().sum()
    miss = miss[miss > 0]
    if miss.empty:
        print(f"{name}: no NaNs")
    else:
        print(f"\n{name} missing:")
        print(pd.DataFrame({"count": miss, "pct": (miss / len(df) * 100).round(2)}))

print("=" * 60)
print("MISSING VALUES (raw)")
print("=" * 60)
missing_report(train, "TRAIN")
missing_report(test, "TEST")
missing_report(weather, "WEATHER")
missing_report(prices, "PRICES")

print("\n" + "=" * 60)
print("SENTINEL -999 COUNTS")
print("=" * 60)
for name, df in [("TRAIN", train), ("TEST", test), ("WEATHER", weather), ("PRICES", prices)]:
    print(f"{name}: {(df == -999).sum().sum()} cells equal to -999")

print("\n" + "=" * 60)
print("DUPLICATE ROWS / KEYS")
print("=" * 60)
print("Train full-row dups:", train.duplicated().sum())
print("Test  full-row dups:", test.duplicated().sum())
print("Train duplicate plot_id:", train["plot_id"].duplicated().sum())
print("Test  duplicate plot_id:", test["plot_id"].duplicated().sum())
print("Weather dups on (region,year,month):", weather.duplicated(["region","year","month"]).sum())
print("Price   dups on (crop,region,year):", prices.duplicated(["crop_type","region","year"]).sum())

print("\n" + "=" * 60)
print("CATEGORICAL INCONSISTENCIES (raw unique values)")
print("=" * 60)
print("TRAIN regions :", sorted(train["region"].astype(str).unique().tolist()))
print("TEST  regions :", sorted(test["region"].astype(str).unique().tolist()))
print("WEATHER regions:", sorted(weather["region"].astype(str).unique().tolist()))
print("TRAIN crops   :", sorted(train["crop_type"].astype(str).unique().tolist()))
print("TEST  crops   :", sorted(test["crop_type"].astype(str).unique().tolist()))
print("PRICE crops   :", sorted(prices["crop_type"].astype(str).unique().tolist()))
print("TRAIN planting_month:", sorted(train["planting_month"].astype(str).unique().tolist()))
print("WEATHER month:", sorted(weather["month"].astype(str).unique().tolist()))

============================================================
MISSING VALUES (raw)
============================================================

TRAIN missing:
                      count   pct
rainfall_mm_season      449  2.98
fertilizer_kg_per_ha    748  4.96
soil_quality_index      608  4.03

TEST missing:
                      count   pct
rainfall_mm_season      125  3.33
fertilizer_kg_per_ha    189  5.04
soil_quality_index      125  3.33

WEATHER missing:
                     count   pct
avg_temp_c               1  0.43
monthly_rainfall_mm      2  0.86

PRICES missing:
                        count  pct
price_birr_per_quintal      4  4.0

============================================================
SENTINEL -999 COUNTS
============================================================
TRAIN: 788 cells equal to -999
TEST: 180 cells equal to -999
WEATHER: 0 cells equal to -999
PRICES: 0 cells equal to -999

============================================================
DUPLICATE ROWS / KEYS
============================================================
Train full-row dups: 0
Test  full-row dups: 0
Train duplicate plot_id: 0
Test  duplicate plot_id: 0
Weather dups on (region,year,month): 6
Price   dups on (crop,region,year): 0

============================================================
CATEGORICAL INCONSISTENCIES (raw unique values)
============================================================
TRAIN regions : ['AMHARA', 'Amhara', 'Amhara ', 'OROMIA', 'Oromia', 'Oromia ', 'SNNPR', 'SNNPR ', 'SOMALI', 'Somali', 'Somali ', 'TIGRAY', 'Tigray', 'Tigray ', 'amhara', 'oromia', 'snnpr', 'somali', 'tigray']
TEST  regions : ['AMHARA', 'Amhara', 'Amhara ', 'OROMIA', 'Oromia', 'Oromia ', 'SNNPR', 'SNNPR ', 'SOMALI', 'Somali', 'Somali ', 'TIGRAY', 'Tigray', 'Tigray ', 'amhara', 'oromia', 'snnpr', 'somali', 'tigray']
WEATHER regions: ['AMH', 'Amhara', 'Amhara ', 'ORO', 'Oromia', 'Oromia ', 'SNNP', 'SNNPR', 'SNNPR ', 'SOM', 'Somali', 'Somali ', 'TIG', 'Tigray', 'Tigray ', 'amhara', 'oromia', 'snnpr', 'somali', 'tigray']
TRAIN crops   : [' barley ', ' maize ', ' sorghum ', ' teff ', ' wheat ', 'BARLEY', 'Barley', 'MAIZE', 'Maize', 'SORGHUM', 'Sorghum', 'TEFF', 'Tef', 'Teff', 'WHEAT', 'Wheat', 'barley', 'maize', 'sorghum', 'teff', 'wheat']
TEST  crops   : [' barley ', ' maize ', ' sorghum ', ' teff ', ' wheat ', 'BARLEY', 'Barley', 'MAIZE', 'Maize', 'SORGHUM', 'Sorghum', 'TEFF', 'Tef', 'Teff', 'WHEAT', 'Wheat', 'barley', 'maize', 'sorghum', 'teff', 'wheat']
PRICE crops   : [' barley ', ' maize ', ' sorghum ', ' teff ', ' wheat ', 'Barley', 'Maize', 'Sorghum', 'Wheat', 'barley', 'maize', 'sorghum', 'teff', 'wheat']
TRAIN planting_month: ['Aug', 'Feb', 'Jul', 'Jun', 'Mar']
WEATHER month: ['Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep']

In [4]:
# Formal Cleaning Log
# Counts are computed on the raw frames above; they will be re-verified after fixes.

cleaning_log = pd.DataFrame([
    # Plot files (≥4 issues)
    {
        "file": "crop_yield_train / leaderboard_test",
        "column(s)": "pest_disease_flag (and others)",
        "issue_type": "Sentinel value -999",
        "rows_affected": f"~{(train == -999).sum().sum() + (test == -999).sum().sum()} cells",
        "pct": "small %",
        "fix_applied": "Replace -999 / '-999' / 'NA' etc. with np.nan",
        "why": "Sentinels are not valid measurements; treat as missing so median/mode imputation works."
    },
    {
        "file": "crop_yield_train / leaderboard_test",
        "column(s)": "region, crop_type, planting_month",
        "issue_type": "Inconsistent casing / whitespace / abbreviations",
        "rows_affected": "majority of rows",
        "pct": ">50%",
        "fix_applied": "str.strip().str.lower() + explicit map (ORO→oromia, AMH→amhara, tef→teff, …)",
        "why": "Join keys must match exactly across tables; mixed case and abbreviations break merges."
    },
    {
        "file": "crop_yield_train / leaderboard_test",
        "column(s)": "farm_size_ha, fertilizer_kg_per_ha, rainfall_mm_season, altitude_m",
        "issue_type": "Implausible / extreme values (e.g. farm_size > 40 ha, fertilizer > 500 kg/ha)",
        "rows_affected": "dozens of rows",
        "pct": "<1%",
        "fix_applied": "Cap at train-derived 99th percentile (or domain upper bound) after imputation",
        "why": "Extreme outliers distort tree splits and linear coefficients; capping preserves rank while limiting leverage."
    },
    {
        "file": "crop_yield_train / leaderboard_test",
        "column(s)": "plot_id",
        "issue_type": "Possible duplicate plot_ids / full-row duplicates",
        "rows_affected": "checked at load",
        "pct": "0–few",
        "fix_applied": "drop_duplicates(subset=['plot_id'], keep='first')",
        "why": "Each plot must appear once for scoring and for many-to-one joins."
    },
    # Weather (≥2)
    {
        "file": "regional_weather.csv",
        "column(s)": "region",
        "issue_type": "Inconsistent region labels (SOM, AMH, Oromia, …)",
        "rows_affected": "many",
        "pct": ">30%",
        "fix_applied": "Same region_map as plot tables → canonical lowercase names",
        "why": "Weather must join on region; mismatched labels produce null weather features."
    },
    {
        "file": "regional_weather.csv",
        "column(s)": "region + year + month",
        "issue_type": "Duplicate (region, year, month) keys",
        "rows_affected": "few",
        "pct": "<5%",
        "fix_applied": "groupby(['region','year','month']).agg(mean)",
        "why": "Many-to-one join from plot→weather requires unique keys; duplicates inflate row counts."
    },
    # Prices (≥2)
    {
        "file": "market_prices.csv",
        "column(s)": "price_birr_per_quintal",
        "issue_type": "Missing prices + possible unit mix-up (orders of magnitude off)",
        "rows_affected": "several rows",
        "pct": "~5-15%",
        "fix_applied": "Median imputation by (crop, region) from train years; flag / correct unit outliers if detected",
        "why": "Price is used only for analysis/demo (never as model feature). Must be complete and in consistent units for revenue calculations."
    },
    {
        "file": "market_prices.csv",
        "column(s)": "crop_type, region",
        "issue_type": "Inconsistent labels (same as plot tables)",
        "rows_affected": "many",
        "pct": ">30%",
        "fix_applied": "Identical strip/lower + crop_map / region_map",
        "why": "Price lookup for demo and revenue analysis requires exact key match."
    },
])

display(cleaning_log)
cleaning_log.to_csv(PROCESSED_DIR / "A1_cleaning_log.csv", index=False)
print("✓ A1 cleaning log saved")

,file,column(s),issue_type,rows_affected,pct,fix_applied,why
0,crop_yield_train / leaderboard_test,pest_disease_flag (and others),Sentinel value -999,~968 cells,small %,Replace -999 / '-999' / 'NA' etc. with np.nan,Sentinels are not valid measurements; treat as...
1,crop_yield_train / leaderboard_test,"region, crop_type, planting_month",Inconsistent casing / whitespace / abbreviations,majority of rows,>50%,str.strip().str.lower() + explicit map (ORO→or...,Join keys must match exactly across tables; mi...
2,crop_yield_train / leaderboard_test,"farm_size_ha, fertilizer_kg_per_ha, rainfall_m...",Implausible / extreme values (e.g. farm_size >...,dozens of rows,<1%,Cap at train-derived 99th percentile (or domai...,Extreme outliers distort tree splits and linea...
3,crop_yield_train / leaderboard_test,plot_id,Possible duplicate plot_ids / full-row duplicates,checked at load,0–few,"drop_duplicates(subset=['plot_id'], keep='first')",Each plot must appear once for scoring and for...
4,regional_weather.csv,region,"Inconsistent region labels (SOM, AMH, Oromia, …)",many,>30%,Same region_map as plot tables → canonical low...,Weather must join on region; mismatched labels...
5,regional_weather.csv,region + year + month,"Duplicate (region, year, month) keys",few,<5%,"groupby(['region','year','month']).agg(mean)",Many-to-one join from plot→weather requires un...
6,market_prices.csv,price_birr_per_quintal,Missing prices + possible unit mix-up (orders ...,several rows,~5-15%,"Median imputation by (crop, region) from train...",Price is used only for analysis/demo (never as...
7,market_prices.csv,"crop_type, region",Inconsistent labels (same as plot tables),many,>30%,Identical strip/lower + crop_map / region_map,Price lookup for demo and revenue analysis req...

✓ A1 cleaning log saved

## A2 — Key Standardization Proof

Show unique values **before** and **after** for `region` (all three tables) and `crop_type` (plot + price).  
After cleaning every table must share the identical region set; plot & price must share the identical crop set.

In [5]:
# Capture BEFORE snapshots
region_before = {
    "train": sorted(train["region"].astype(str).str.strip().str.lower().unique().tolist()),
    "test":  sorted(test["region"].astype(str).str.strip().str.lower().unique().tolist()),
    "weather": sorted(weather["region"].astype(str).str.strip().str.lower().unique().tolist()),
    "prices": sorted(prices["region"].astype(str).str.strip().str.lower().unique().tolist()),
}
crop_before = {
    "train": sorted(train["crop_type"].astype(str).str.strip().str.lower().unique().tolist()),
    "test":  sorted(test["crop_type"].astype(str).str.strip().str.lower().unique().tolist()),
    "prices": sorted(prices["crop_type"].astype(str).str.strip().str.lower().unique().tolist()),
}

print("REGION unique values BEFORE standardization:")
for k, v in region_before.items():
    print(f"  {k}: {v}")

print("\nCROP unique values BEFORE standardization:")
for k, v in crop_before.items():
    print(f"  {k}: {v}")

REGION unique values BEFORE standardization:
  train: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']
  test: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']
  weather: ['amh', 'amhara', 'oro', 'oromia', 'snnp', 'snnpr', 'som', 'somali', 'tig', 'tigray']
  prices: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']

CROP unique values BEFORE standardization:
  train: ['barley', 'maize', 'sorghum', 'tef', 'teff', 'wheat']
  test: ['barley', 'maize', 'sorghum', 'tef', 'teff', 'wheat']
  prices: ['barley', 'maize', 'sorghum', 'teff', 'wheat']

In [6]:
# ---------- Apply standardization (single place) ----------
REGION_MAP = {
    "oro": "oromia", "oromia": "oromia",
    "amh": "amhara", "amhara": "amhara",
    "snnp": "snnpr", "snnpr": "snnpr",
    "som": "somali", "somali": "somali",
    "tig": "tigray", "tigray": "tigray",
}
CROP_MAP = {
    "tef": "teff", "teff": "teff",
    "wheat": "wheat", "maize": "maize",
    "sorghum": "sorghum", "barley": "barley",
}
MONTH_MAP = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4,
    "may": 5, "jun": 6, "jul": 7, "aug": 8,
    "sep": 9, "oct": 10, "nov": 11, "dec": 12,
}

def standardize_text(df):
    for col in ["region", "crop_type", "planting_month", "month"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.lower()
    if "region" in df.columns:
        df["region"] = df["region"].replace(REGION_MAP)
    if "crop_type" in df.columns:
        df["crop_type"] = df["crop_type"].replace(CROP_MAP)
    return df

for df in [train, test, weather, prices]:
    standardize_text(df)

# Planting / weather month numerics
train["planting_month_num"] = train["planting_month"].map(MONTH_MAP)
test["planting_month_num"]  = test["planting_month"].map(MONTH_MAP)
weather["month_num"]        = weather["month"].map(MONTH_MAP)

# AFTER snapshots
region_after = {
    "train": sorted(train["region"].dropna().unique().tolist()),
    "test":  sorted(test["region"].dropna().unique().tolist()),
    "weather": sorted(weather["region"].dropna().unique().tolist()),
    "prices": sorted(prices["region"].dropna().unique().tolist()),
}
crop_after = {
    "train": sorted(train["crop_type"].dropna().unique().tolist()),
    "test":  sorted(test["crop_type"].dropna().unique().tolist()),
    "prices": sorted(prices["crop_type"].dropna().unique().tolist()),
}

print("REGION unique values AFTER standardization:")
for k, v in region_after.items():
    print(f"  {k}: {v}")

print("\nCROP unique values AFTER standardization:")
for k, v in crop_after.items():
    print(f"  {k}: {v}")

# Proof of identical sets
assert region_after["train"] == region_after["test"] == region_after["weather"] == region_after["prices"]
assert crop_after["train"] == crop_after["test"] == crop_after["prices"]
print("\n✓ All tables share identical region labels")
print("✓ Plot and price tables share identical crop labels")

REGION unique values AFTER standardization:
  train: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']
  test: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']
  weather: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']
  prices: ['amhara', 'oromia', 'snnpr', 'somali', 'tigray']

CROP unique values AFTER standardization:
  train: ['barley', 'maize', 'sorghum', 'teff', 'wheat']
  test: ['barley', 'maize', 'sorghum', 'teff', 'wheat']
  prices: ['barley', 'maize', 'sorghum', 'teff', 'wheat']

✓ All tables share identical region labels
✓ Plot and price tables share identical crop labels

## Cleaning Steps (missing, duplicates, sentinels, outliers)

Imputation statistics are learned **only from train** and applied to test (Rule 6).

In [7]:
# 1. Sentinels → NaN
for df in [train, test, weather, prices]:
    df.replace([-999, "-999", "NA", "N/A", "na", "n/a", ""], np.nan, inplace=True)

# 2. Force numeric where appropriate
id_like = {"plot_id", "region", "crop_type", "planting_month", "month"}
for df in [train, test, weather, prices]:
    for col in df.columns:
        if col not in id_like:
            df[col] = pd.to_numeric(df[col], errors="coerce")

# 3. Remove exact duplicate rows and duplicate keys
train   = train.drop_duplicates().drop_duplicates(subset=["plot_id"], keep="first").reset_index(drop=True)
test    = test.drop_duplicates().drop_duplicates(subset=["plot_id"], keep="first").reset_index(drop=True)
weather = weather.drop_duplicates().reset_index(drop=True)
prices  = prices.drop_duplicates().reset_index(drop=True)

# Aggregate any remaining weather / price key collisions
weather = (weather.groupby(["region", "year", "month", "month_num"], as_index=False)
           .agg({"avg_temp_c": "mean", "monthly_rainfall_mm": "mean", "extreme_heat_days": "mean"}))
prices  = (prices.groupby(["region", "crop_type", "year"], as_index=False)
           ["price_birr_per_quintal"].mean())

print("After dedup shapes:", train.shape, test.shape, weather.shape, prices.shape)

# 4. Impute numeric columns with TRAIN medians only
numeric_cols_train = train.select_dtypes(include=np.number).columns.tolist()
# do not impute the target with anything other than its own median if needed
train_medians = train[numeric_cols_train].median()

for col in numeric_cols_train:
    if col == "yield_tons_per_ha":
        continue
    if train[col].isna().any():
        train[col] = train[col].fillna(train_medians[col])
    if col in test.columns and test[col].isna().any():
        test[col] = test[col].fillna(train_medians[col])

# Weather / prices: simple median (small tables, no leakage into model features)
for df in [weather, prices]:
    for col in df.select_dtypes(include=np.number).columns:
        if df[col].isna().any():
            df[col] = df[col].fillna(df[col].median())

# 5. Categorical mode fill (rare)
for df in [train, test, weather, prices]:
    for col in df.select_dtypes(include="object").columns:
        if df[col].isna().any():
            mode_val = df[col].mode()
            if len(mode_val):
                df[col] = df[col].fillna(mode_val[0])

# 6. Light outlier capping on train-derived 99th percentile (plot features only)
cap_cols = ["farm_size_ha", "fertilizer_kg_per_ha", "rainfall_mm_season", "labor_days_per_ha", "distance_to_market_km"]
caps = {}
for col in cap_cols:
    if col in train.columns:
        caps[col] = train[col].quantile(0.99)
        train[col] = train[col].clip(upper=caps[col])
        if col in test.columns:
            test[col] = test[col].clip(upper=caps[col])

print("\nMissing after cleaning:")
print("TRAIN:", train.isna().sum().sum())
print("TEST :", test.isna().sum().sum())
print("WEATHER:", weather.isna().sum().sum())
print("PRICES :", prices.isna().sum().sum())
print("Target missing:", train["yield_tons_per_ha"].isna().sum())

After dedup shapes: (15090, 16) (3750, 15) (226, 7) (100, 4)

Missing after cleaning:
TRAIN: 0
TEST : 0
WEATHER: 0
PRICES : 0
Target missing: 0

## A3 — Join Map & Diagram

**Left table:** plot-level survey (train / test) — one row per plot; this is the grain we need for modeling and scoring.

**Join 1 — Weather (many-to-one):**
- Keys: `region` + `survey_year` (= weather `year`) + growing-season months derived from `planting_month_num`.
- Growing-season window rule: **planting month + the following 3 months** (handles year wrap-around).
- Aggregation: mean temperature, min/max temperature, total & mean rainfall, sum of extreme-heat days, count of months available.
- Expected cardinality: many plots → one seasonal weather summary.

**Join 2 — Prices (many-to-one, analysis/demo only):**
- Keys: `region` + `crop_type` + `survey_year`.
- Price is **never** used as a model feature (Rule / leakage).
- Expected cardinality: many plots → one price.

```
plot (left)  ──region, year, growing months──►  weather (aggregated to season)
     │
     └──region, crop, year──►  prices  (lookup only for revenue / demo)
```

## A4 — Join Audit & A5 — Join Proof

In [10]:
# ---------- Growing-season helper ----------
def get_growing_months(planting_month):
    """Planting month + next 3 months (1-12, wraps around)."""
    if pd.isna(planting_month):
        return []
    pm = int(planting_month)
    return [((pm - 1 + i) % 12) + 1 for i in range(4)]

print("Example windows:")
for m in [2, 6, 8, 11]:
    print(f"  planting {m} → months {get_growing_months(m)}")

# ---------- Build seasonal weather features ----------
def create_weather_features(farm_data, weather_data):
    records = []
    for _, row in farm_data.iterrows():
        region = row["region"]
        year   = row["survey_year"]
        pm     = row["planting_month_num"]
        months = get_growing_months(pm)

        if not months:
            records.append({
                "season_temp_mean": np.nan,
                "season_temp_min": np.nan,
                "season_temp_max": np.nan,
                "season_rain_total": np.nan,
                "season_rain_mean": np.nan,
                "season_heat_days": np.nan,
                "weather_months_available": 0,
            })
            continue

        w = weather_data[
            (weather_data["region"] == region) &
            (weather_data["year"] == year) &
            (weather_data["month_num"].isin(months))
        ]
        records.append({
            "season_temp_mean": w["avg_temp_c"].mean(),
            "season_temp_min":  w["avg_temp_c"].min(),
            "season_temp_max":  w["avg_temp_c"].max(),
            "season_rain_total": w["monthly_rainfall_mm"].sum(),
            "season_rain_mean":  w["monthly_rainfall_mm"].mean(),
            "season_heat_days":  w["extreme_heat_days"].sum(),
            "weather_months_available": len(w),
        })
    return pd.DataFrame(records)

n_train_before = len(train)
n_test_before  = len(test)

train_weather = create_weather_features(train, weather)
test_weather  = create_weather_features(test, weather)

# Drop any previously attached weather columns so re-runs are safe
weather_features = [
    "season_temp_mean", "season_temp_min", "season_temp_max",
    "season_rain_total", "season_rain_mean", "season_heat_days",
    "weather_months_available"
]
train = train.drop(columns=[c for c in weather_features if c in train.columns], errors="ignore")
test  = test.drop(columns=[c for c in weather_features if c in test.columns], errors="ignore")

# Attach (axis=1 concat preserves row order / count)
train = pd.concat([train.reset_index(drop=True), train_weather], axis=1)
test  = pd.concat([test.reset_index(drop=True),  test_weather],  axis=1)

assert len(train) == n_train_before, "Train row count changed by weather join!"
assert len(test)  == n_test_before,  "Test row count changed by weather join!"

weather_features = [
    "season_temp_mean", "season_temp_min", "season_temp_max",
    "season_rain_total", "season_rain_mean", "season_heat_days",
    "weather_months_available"
]

print("\n--- A4 Weather Join Audit ---")
print(f"Train rows before/after: {n_train_before} / {len(train)}")
print(f"Test  rows before/after: {n_test_before} / {len(test)}")
print("\nWeather months available (train):")
print(train["weather_months_available"].value_counts().sort_index())
print("\nPlots with < 4 months of weather:", (train["weather_months_available"] < 4).sum())
print("Match rate (at least 1 month):", (train["weather_months_available"] >= 1).mean().round(4))

# Fill any residual NaNs in weather features with train medians
for col in weather_features:
    med = train[col].median()
    train[col] = train[col].fillna(med)
    test[col]  = test[col].fillna(med)

Example windows:
  planting 2 → months [2, 3, 4, 5]
  planting 6 → months [6, 7, 8, 9]
  planting 8 → months [8, 9, 10, 11]
  planting 11 → months [11, 12, 1, 2]

--- A4 Weather Join Audit ---
Train rows before/after: 15090 / 15090
Test  rows before/after: 3750 / 3750

Weather months available (train):
weather_months_available
2      448
3     2477
4    12165
Name: count, dtype: int64

Plots with < 4 months of weather: 2925
Match rate (at least 1 month): 1.0

In [11]:
# ---------- A5 Join Proof: 3 concrete plots ----------
sample_plots = train.sample(3, random_state=RANDOM_STATE)[
    ["plot_id", "region", "survey_year", "planting_month", "planting_month_num"]
    + weather_features
].copy()

print("Three example plots after weather join:")
display(sample_plots)

for _, row in sample_plots.iterrows():
    months = get_growing_months(row["planting_month_num"])
    w = weather[
        (weather["region"] == row["region"]) &
        (weather["year"] == row["survey_year"]) &
        (weather["month_num"].isin(months))
    ]
    print(f"\nPlot {row['plot_id']} | region={row['region']} | year={row['survey_year']} | plant={row['planting_month']}")
    print(f"  Growing months: {months}")
    print(f"  Weather rows pulled ({len(w)}):")
    display(w[["region", "year", "month", "avg_temp_c", "monthly_rainfall_mm", "extreme_heat_days"]])
    print(f"  → season_temp_mean = {row['season_temp_mean']:.2f}")
    print(f"  → season_rain_total = {row['season_rain_total']:.1f}")
    print(f"  → season_heat_days  = {row['season_heat_days']:.0f}")

Three example plots after weather join:

,plot_id,region,survey_year,planting_month,planting_month_num,season_temp_mean,season_temp_min,season_temp_max,season_rain_total,season_rain_mean,season_heat_days,weather_months_available
339,PLOT-014567,oromia,2021,jul,7,18.7500,17.6,21.4,394.9,98.725,1.0,4
7457,PLOT-011066,oromia,2021,mar,3,19.7000,17.2,20.8,322.4,80.600,0.0,4
6092,PLOT-014009,somali,2022,jun,6,24.7875,23.1,25.5,253.5,63.375,16.0,4

Plot PLOT-014567 | region=oromia | year=2021 | plant=jul
  Growing months: [7, 8, 9, 10]
  Weather rows pulled (4):

    region  year month  avg_temp_c  monthly_rainfall_mm  extreme_heat_days
46  oromia  2021   aug        17.6                121.5                0.0
50  oromia  2021   jul        17.8                111.9                1.0
55  oromia  2021   oct        21.4                 14.4                0.0
56  oromia  2021   sep        18.2                147.1                0.0

  → season_temp_mean = 18.75
  → season_rain_total = 394.9
  → season_heat_days  = 1

Plot PLOT-011066 | region=oromia | year=2021 | plant=mar
  Growing months: [3, 4, 5, 6]
  Weather rows pulled (4):

    region  year month  avg_temp_c  monthly_rainfall_mm  extreme_heat_days
45  oromia  2021   apr        20.8                 60.7                0.0
51  oromia  2021   jun        17.2                165.3                0.0
52  oromia  2021   mar        20.2                 48.2                0.0
53  oromia  2021   may        20.6                 48.2                0.0

  → season_temp_mean = 19.70
  → season_rain_total = 322.4
  → season_heat_days  = 0

Plot PLOT-014009 | region=somali | year=2022 | plant=jun
  Growing months: [6, 7, 8, 9]
  Weather rows pulled (4):

     region  year month  avg_temp_c  monthly_rainfall_mm  extreme_heat_days
150  somali  2022   aug       25.10                 66.0                2.0
154  somali  2022   jul       25.50                 47.7                4.0
155  somali  2022   jun       25.45                 58.2                7.0
159  somali  2022   sep       23.10                 81.6                3.0

  → season_temp_mean = 24.79
  → season_rain_total = 253.5
  → season_heat_days  = 16

In [12]:
# ---------- Price join (analysis / demo only — NOT model features) ----------
n_before = len(train)
train = train.merge(
    prices.rename(columns={"year": "survey_year"}),
    on=["region", "crop_type", "survey_year"],
    how="left"
)
test = test.merge(
    prices.rename(columns={"year": "survey_year"}),
    on=["region", "crop_type", "survey_year"],
    how="left"
)
assert len(train) == n_before, "Price join changed train row count — check duplicate keys"

print("Price match rate (train):", train["price_birr_per_quintal"].notna().mean().round(4))
print("Unmatched price rows (train):", train["price_birr_per_quintal"].isna().sum())
# Fill unmatched prices with overall train median for demo convenience
price_med = train["price_birr_per_quintal"].median()
train["price_birr_per_quintal"] = train["price_birr_per_quintal"].fillna(price_med)
test["price_birr_per_quintal"]  = test["price_birr_per_quintal"].fillna(price_med)

Price match rate (train): 1.0
Unmatched price rows (train): 0

## A6 — Feature Engineering Table

≥6 engineered features: ≥3 from weather, ≥1 ratio/interaction, ≥1 from planting_month.

In [13]:
# Weather-derived (already created by join):
#   season_temp_mean, season_temp_min, season_temp_max,
#   season_rain_total, season_rain_mean, season_heat_days, weather_months_available

# Drop previously engineered columns so re-runs are safe
eng_cols = [
    "fertilizer_per_ha", "labor_per_ha", "market_distance_per_ha",
    "rainfall_difference", "rainfall_ratio",
    "rain_temp_interaction", "heat_temp_interaction", "heat_days_per_month",
    "planting_month_sin", "planting_month_cos"
]
train = train.drop(columns=[c for c in eng_cols if c in train.columns], errors="ignore")
test  = test.drop(columns=[c for c in eng_cols if c in test.columns], errors="ignore")


for df in [train, test]:
    # Ratio / intensity
    df["fertilizer_per_ha"] = df["fertilizer_kg_per_ha"] / df["farm_size_ha"].replace(0, np.nan)
    df["labor_per_ha"]      = df["labor_days_per_ha"]   / df["farm_size_ha"].replace(0, np.nan)
    df["market_distance_per_ha"] = df["distance_to_market_km"] / df["farm_size_ha"].replace(0, np.nan)

    # Reported vs station rainfall
    df["rainfall_difference"] = df["rainfall_mm_season"] - df["season_rain_total"]
    df["rainfall_ratio"]      = df["rainfall_mm_season"] / df["season_rain_total"].replace(0, np.nan)

    # Interactions
    df["rain_temp_interaction"] = df["season_rain_total"] * df["season_temp_mean"]
    df["heat_temp_interaction"] = df["season_heat_days"]  * df["season_temp_mean"]
    df["heat_days_per_month"]   = df["season_heat_days"]  / df["weather_months_available"].replace(0, np.nan)

    # Planting-month cyclic encoding
    df["planting_month_sin"] = np.sin(2 * np.pi * df["planting_month_num"] / 12)
    df["planting_month_cos"] = np.cos(2 * np.pi * df["planting_month_num"] / 12)

# Fill any new NaNs created by division with train medians
new_cols = [
    "fertilizer_per_ha", "labor_per_ha", "market_distance_per_ha",
    "rainfall_difference", "rainfall_ratio",
    "rain_temp_interaction", "heat_temp_interaction", "heat_days_per_month",
    "planting_month_sin", "planting_month_cos"
]
for col in new_cols:
    med = train[col].median()
    train[col] = train[col].fillna(med)
    test[col]  = test[col].fillna(med)

feature_engineering_table = pd.DataFrame([
    {"name": "season_temp_mean", "formula": "mean(avg_temp_c over growing season)", "source": "weather", "why": "Temperature drives phenology and yield potential"},
    {"name": "season_rain_total", "formula": "sum(monthly_rainfall_mm over growing season)", "source": "weather", "why": "Water availability is a primary yield driver"},
    {"name": "season_heat_days", "formula": "sum(extreme_heat_days over growing season)", "source": "weather", "why": "Heat stress reduces grain filling"},
    {"name": "rainfall_difference", "formula": "rainfall_mm_season - season_rain_total", "source": "plot + weather", "why": "Captures discrepancy between farmer report and station data"},
    {"name": "rain_temp_interaction", "formula": "season_rain_total * season_temp_mean", "source": "weather", "why": "Joint climate effect; rain matters more in certain temperature regimes"},
    {"name": "fertilizer_per_ha", "formula": "fertilizer_kg_per_ha / farm_size_ha", "source": "plot", "why": "Intensity of input use may matter more than absolute rate"},
    {"name": "planting_month_sin / cos", "formula": "sin/cos(2π * planting_month_num / 12)", "source": "planting_month", "why": "Cyclic encoding lets the model learn seasonal timing without ordinal assumption"},
    {"name": "heat_days_per_month", "formula": "season_heat_days / weather_months_available", "source": "weather", "why": "Normalises heat exposure for incomplete season coverage"},
])
display(feature_engineering_table)
print(f"Train shape after FE: {train.shape}")
print(f"Test  shape after FE: {test.shape}")

,name,formula,source,why
0,season_temp_mean,mean(avg_temp_c over growing season),weather,Temperature drives phenology and yield potential
1,season_rain_total,sum(monthly_rainfall_mm over growing season),weather,Water availability is a primary yield driver
2,season_heat_days,sum(extreme_heat_days over growing season),weather,Heat stress reduces grain filling
3,rainfall_difference,rainfall_mm_season - season_rain_total,plot + weather,Captures discrepancy between farmer report and...
4,rain_temp_interaction,season_rain_total * season_temp_mean,weather,Joint climate effect; rain matters more in cer...
5,fertilizer_per_ha,fertilizer_kg_per_ha / farm_size_ha,plot,Intensity of input use may matter more than ab...
6,planting_month_sin / cos,sin/cos(2π * planting_month_num / 12),planting_month,Cyclic encoding lets the model learn seasonal ...
7,heat_days_per_month,season_heat_days / weather_months_available,weather,Normalises heat exposure for incomplete season...

Train shape after FE: (15090, 34)
Test  shape after FE: (3750, 33)

## A7 — Integrity Checks

≥5 automated checks that print PASS / FAIL.

In [14]:
target = "yield_tons_per_ha"
ALLOWED_REGIONS = {"oromia", "amhara", "snnpr", "tigray", "somali"}
ALLOWED_CROPS   = {"teff", "wheat", "maize", "sorghum", "barley"}

def check(name, condition):
    status = "PASS" if condition else "FAIL"
    print(f"[{status}] {name}")
    return condition

print("=" * 60)
print("A7 INTEGRITY CHECKS")
print("=" * 60)

results = []
results.append(check("plot_id unique in train", train["plot_id"].is_unique))
results.append(check("plot_id unique in test",  test["plot_id"].is_unique))
results.append(check("row count unchanged by joins (train)", len(train) == n_train_before))
results.append(check("row count unchanged by joins (test)",  len(test)  == n_test_before))
results.append(check("no missing target in train", train[target].notna().all()))
results.append(check("target absent from test", target not in test.columns))

# Feature columns identical (excluding target & price)
model_exclude = {target, "price_birr_per_quintal", "plot_id"}
train_feats = [c for c in train.columns if c not in model_exclude]
test_feats  = [c for c in test.columns  if c not in model_exclude]
# Align: test should have same model features
results.append(check("train/test share same model feature set", set(train_feats) == set(test_feats)))

results.append(check("all regions in allowed set (train)", set(train["region"].unique()) <= ALLOWED_REGIONS))
results.append(check("all crops in allowed set (train)",   set(train["crop_type"].unique()) <= ALLOWED_CROPS))
results.append(check("yield >= 0", (train[target] >= 0).all()))
results.append(check("price > 0 where present", (train["price_birr_per_quintal"] > 0).all()))
results.append(check("at least one weather-derived feature present", "season_temp_mean" in train.columns))

print("\n" + ("✓ ALL CHECKS PASSED" if all(results) else "⚠ SOME CHECKS FAILED"))

============================================================
A7 INTEGRITY CHECKS
============================================================
[PASS] plot_id unique in train
[PASS] plot_id unique in test
[PASS] row count unchanged by joins (train)
[PASS] row count unchanged by joins (test)
[PASS] no missing target in train
[PASS] target absent from test
[PASS] train/test share same model feature set
[PASS] all regions in allowed set (train)
[PASS] all crops in allowed set (train)
[PASS] yield >= 0
[PASS] price > 0 where present
[PASS] at least one weather-derived feature present

✓ ALL CHECKS PASSED

## A8 — Master Tables & Data Dictionary

In [15]:
# Drop price from modeling tables (keep a copy for analysis/demo if needed)
master_train = train.drop(columns=["price_birr_per_quintal"], errors="ignore").copy()
master_test  = test.drop(columns=["price_birr_per_quintal"], errors="ignore").copy()

# Ensure identical feature column order (target last in train)
feature_cols = [c for c in master_train.columns if c != target]
master_train = master_train[feature_cols + [target]]
master_test  = master_test[feature_cols]   # no target

assert list(master_train.drop(columns=[target]).columns) == list(master_test.columns)

master_train.to_csv(PROCESSED_DIR / "master_train.csv", index=False)
master_test.to_csv(PROCESSED_DIR / "master_test.csv", index=False)

print("Master train:", master_train.shape)
print("Master test :", master_test.shape)
print("✓ Saved master_train.csv and master_test.csv")

Master train: (15090, 33)
Master test : (3750, 32)
✓ Saved master_train.csv and master_test.csv

In [16]:
# Data dictionary
dictionary = {
    "plot_id": {"source": "plot survey", "description": "Unique plot identifier", "derived": "Original"},
    "region": {"source": "plot survey", "description": "Administrative region (standardized)", "derived": "Cleaned + mapped"},
    "crop_type": {"source": "plot survey", "description": "Crop grown (standardized)", "derived": "Cleaned + mapped"},
    "survey_year": {"source": "plot survey", "description": "Survey year 2021-2024", "derived": "Original"},
    "planting_month": {"source": "plot survey", "description": "Planting month name", "derived": "Standardized lowercase"},
    "planting_month_num": {"source": "plot survey", "description": "Planting month as 1-12", "derived": "Mapped from name"},
    "altitude_m": {"source": "plot survey", "description": "Elevation (m)", "derived": "Original"},
    "rainfall_mm_season": {"source": "plot survey", "description": "Farmer-reported seasonal rainfall (mm)", "derived": "Original"},
    "farm_size_ha": {"source": "plot survey", "description": "Farm size (ha)", "derived": "Original (capped)"},
    "fertilizer_kg_per_ha": {"source": "plot survey", "description": "Fertilizer rate (kg/ha)", "derived": "Original (capped)"},
    "improved_seed_used": {"source": "plot survey", "description": "Improved seed used (0/1)", "derived": "Original"},
    "pest_disease_flag": {"source": "plot survey", "description": "Pest/disease observed (0/1)", "derived": "Original (-999→NaN→imputed)"},
    "soil_quality_index": {"source": "plot survey", "description": "Soil quality score 0-1", "derived": "Original"},
    "labor_days_per_ha": {"source": "plot survey", "description": "Labor days per hectare", "derived": "Original"},
    "distance_to_market_km": {"source": "plot survey", "description": "Distance to market (km)", "derived": "Original"},
    "yield_tons_per_ha": {"source": "plot survey", "description": "TARGET — yield in tons per hectare", "derived": "Original (train only)"},
    "season_temp_mean": {"source": "regional_weather", "description": "Mean temperature over growing season (°C)", "derived": "mean of monthly avg_temp_c"},
    "season_temp_min": {"source": "regional_weather", "description": "Min monthly temperature in season (°C)", "derived": "min of monthly avg_temp_c"},
    "season_temp_max": {"source": "regional_weather", "description": "Max monthly temperature in season (°C)", "derived": "max of monthly avg_temp_c"},
    "season_rain_total": {"source": "regional_weather", "description": "Total rainfall over growing season (mm)", "derived": "sum of monthly_rainfall_mm"},
    "season_rain_mean": {"source": "regional_weather", "description": "Mean monthly rainfall in season (mm)", "derived": "mean of monthly_rainfall_mm"},
    "season_heat_days": {"source": "regional_weather", "description": "Total extreme-heat days in season", "derived": "sum of extreme_heat_days"},
    "weather_months_available": {"source": "regional_weather", "description": "Number of months with weather data in window", "derived": "count of matching weather rows"},
    "fertilizer_per_ha": {"source": "engineered", "description": "Fertilizer intensity", "derived": "fertilizer_kg_per_ha / farm_size_ha"},
    "labor_per_ha": {"source": "engineered", "description": "Labor intensity", "derived": "labor_days_per_ha / farm_size_ha"},
    "market_distance_per_ha": {"source": "engineered", "description": "Market distance intensity", "derived": "distance_to_market_km / farm_size_ha"},
    "rainfall_difference": {"source": "engineered", "description": "Reported minus station rainfall", "derived": "rainfall_mm_season - season_rain_total"},
    "rainfall_ratio": {"source": "engineered", "description": "Reported / station rainfall", "derived": "rainfall_mm_season / season_rain_total"},
    "rain_temp_interaction": {"source": "engineered", "description": "Rain × temperature interaction", "derived": "season_rain_total * season_temp_mean"},
    "heat_temp_interaction": {"source": "engineered", "description": "Heat days × temperature", "derived": "season_heat_days * season_temp_mean"},
    "heat_days_per_month": {"source": "engineered", "description": "Heat intensity", "derived": "season_heat_days / weather_months_available"},
    "planting_month_sin": {"source": "engineered", "description": "Cyclic encoding of planting month", "derived": "sin(2π * planting_month_num / 12)"},
    "planting_month_cos": {"source": "engineered", "description": "Cyclic encoding of planting month", "derived": "cos(2π * planting_month_num / 12)"},
}

rows = []
for col in master_train.columns:
    info = dictionary.get(col, {"source": "unknown", "description": "No description", "derived": "Unknown"})
    rows.append({
        "column": col,
        "type": str(master_train[col].dtype),
        "source_file": info["source"],
        "description": info["description"],
        "derivation": info["derived"],
    })

data_dictionary = pd.DataFrame(rows)
display(data_dictionary)
data_dictionary.to_csv(PROCESSED_DIR / "data_dictionary_master.csv", index=False)
print("✓ data_dictionary_master.csv saved")

,column,type,source_file,description,derivation
0,plot_id,str,plot survey,Unique plot identifier,Original
1,region,str,plot survey,Administrative region (standardized),Cleaned + mapped
2,crop_type,str,plot survey,Crop grown (standardized),Cleaned + mapped
3,survey_year,int64,plot survey,Survey year 2021-2024,Original
4,planting_month,str,plot survey,Planting month name,Standardized lowercase
5,altitude_m,float64,plot survey,Elevation (m),Original
6,rainfall_mm_season,float64,plot survey,Farmer-reported seasonal rainfall (mm),Original
7,farm_size_ha,float64,plot survey,Farm size (ha),Original (capped)
8,fertilizer_kg_per_ha,float64,plot survey,Fertilizer rate (kg/ha),Original (capped)
9,improved_seed_used,int64,plot survey,Improved seed used (0/1),Original
10,pest_disease_flag,float64,plot survey,Pest/disease observed (0/1),Original (-999→NaN→imputed)
11,soil_quality_index,float64,plot survey,Soil quality score 0-1,Original
12,labor_days_per_ha,float64,plot survey,Labor days per hectare,Original
13,distance_to_market_km,float64,plot survey,Distance to market (km),Original
14,planting_month_num,int64,plot survey,Planting month as 1-12,Mapped from name
15,season_temp_mean,float64,regional_weather,Mean temperature over growing season (°C),mean of monthly avg_temp_c
16,season_temp_min,float64,regional_weather,Min monthly temperature in season (°C),min of monthly avg_temp_c
17,season_temp_max,float64,regional_weather,Max monthly temperature in season (°C),max of monthly avg_temp_c
18,season_rain_total,float64,regional_weather,Total rainfall over growing season (mm),sum of monthly_rainfall_mm
19,season_rain_mean,float64,regional_weather,Mean monthly rainfall in season (mm),mean of monthly_rainfall_mm
20,season_heat_days,float64,regional_weather,Total extreme-heat days in season,sum of extreme_heat_days
21,weather_months_available,int64,regional_weather,Number of months with weather data in window,count of matching weather rows
22,fertilizer_per_ha,float64,engineered,Fertilizer intensity,fertilizer_kg_per_ha / farm_size_ha
23,labor_per_ha,float64,engineered,Labor intensity,labor_days_per_ha / farm_size_ha
24,market_distance_per_ha,float64,engineered,Market distance intensity,distance_to_market_km / farm_size_ha
25,rainfall_difference,float64,engineered,Reported minus station rainfall,rainfall_mm_season - season_rain_total
26,rainfall_ratio,float64,engineered,Reported / station rainfall,rainfall_mm_season / season_rain_total
27,rain_temp_interaction,float64,engineered,Rain × temperature interaction,season_rain_total * season_temp_mean
28,heat_temp_interaction,float64,engineered,Heat days × temperature,season_heat_days * season_temp_mean
29,heat_days_per_month,float64,engineered,Heat intensity,season_heat_days / weather_months_available
30,planting_month_sin,float64,engineered,Cyclic encoding of planting month,sin(2π * planting_month_num / 12)
31,planting_month_cos,float64,engineered,Cyclic encoding of planting month,cos(2π * planting_month_num / 12)
32,yield_tons_per_ha,float64,plot survey,TARGET — yield in tons per hectare,Original (train only)

✓ data_dictionary_master.csv saved

In [17]:
# Final validation
print("=" * 60)
print("FINAL MASTER TABLE VALIDATION")
print("=" * 60)
print("Master train:", master_train.shape)
print("Master test :", master_test.shape)
print("Dictionary  :", data_dictionary.shape)

assert list(master_train.drop(columns=[target]).columns) == list(master_test.columns)
assert target in master_train.columns and target not in master_test.columns
assert "price_birr_per_quintal" not in master_train.columns
assert master_train["plot_id"].is_unique and master_test["plot_id"].is_unique
assert master_train[target].notna().all()

print("\n✓ Same feature columns: PASS")
print("✓ Target only in train: PASS")
print("✓ Price excluded from model tables: PASS")
print("✓ Plot IDs unique: PASS")
print("✓ Training target complete: PASS")
print("\nMASTER TABLES READY")

============================================================
FINAL MASTER TABLE VALIDATION
============================================================
Master train: (15090, 33)
Master test : (3750, 32)
Dictionary  : (33, 5)

✓ Same feature columns: PASS
✓ Target only in train: PASS
✓ Price excluded from model tables: PASS
✓ Plot IDs unique: PASS
✓ Training target complete: PASS

MASTER TABLES READY